### ISSUE TITLE
[BUG]./ecc执行错误，找不到库libclang-13.so.13，该库名称错误，正确的名称应该是libclang.so.13

### ISSUE THREAD

**Issue by 3edc2wsx** [eunomia-bpf/eunomia-bpf#188]
]./ecc执行错误，找不到库libclang-13.so.13，该库名称错误，正确的名称应该是libclang.so.13

[root@localhost ~]#wget https://github.com/eunomia-bpf/eunomia-bpf/releases/latest/download/ecc && chmod +x ./ecc
[root@localhost ~]# ./ecc -h
./ecc: error while loading shared libraries: libclang-13.so.13: cannot open shared object file: No such file or directory

[root@lfbn-idf1-1-1656-18 lib]# clang --version
clang version 13.0.1
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

[root@lfbn-idf1-1-1656-18 lib]# cat /etc/os-release
NAME="openEuler"
VERSION="23.03"
ID="openEuler"
VERSION_ID="23.03"
PRETTY_NAME="openEuler 23.03"
ANSI_COLOR="0;31"

**Comment by ocfox** [comment]
It seems that `libclang-13-dev` uses the wrong symlink to the shared library, we will fix this problem as soon as possible.

**Comment by oluceps** [comment]
As I know on Debian-based linux distros, which also compile env of released binary, has no package provides `libclang.so.13`.
Perhaps you could manually make a symbolic link named as libclang-13.so.13 in any of your library path to solve the problem.

**Comment by 3edc2wsx** [comment]
本地实测，ubuntu上./ecc可以正常执行，openEuler不行，openeuler是基于centos的版本。

**Comment by ocfox** [comment]
> Perhaps you could manually make a symbolic link named libclang-13.so.13 in any of your library paths to solve the problem.

Are you trying this way?
It's should work.

**Comment by oluceps** [comment]
> 本地实测，ubuntu上./ecc可以正常执行，openEuler不行，openeuler是基于centos的版本。重链接后也还是不行，估计要用openeuler编的版本才能在openeuler上使用

You could take a look at [this](https://gitee.com/oluceps/eunomia-bpf/tree/add-pkg/) `v0.3.2` version packaged for openEuler.

Follow these steps after clone the repo:

```
$ rpmdev-setuptree
// ... move tarball and patches into ~/rpmbuild/SOURCES
// ... enter repo
$ rpmbuild -ba eunomia-bpf.spec
// ... then you could find rpm package under ~/rpmbuild/RPMS
```
**Notice**: The version of rust toolchain in openEuler may not meet the minimal requirements.

Since the `latest` release exceeds the file size limit of gitee, [here](https://gitee.com/oluceps/eunomia-bpf/tree/0.3.19/) is the packaged `v0.3.19` but without tarball, need to  add source and vendor cargo deps manually if you want to use the latest.

**Comment by Officeyutong** [comment]
Please re-download https://github.com/eunomia-bpf/eunomia-bpf/issues/188 and retry. We package executables in `AppImage` format to avoid compatible issues now
